version: "3.7"

services:
    app:
        build: ./
        restart: always
        environment:
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: streamify.ssprojects.ca
            LETSENCRYPT_HOST: streamify.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network

networks:
    service-network:
        external: true
