export const search = (query, cb) => {
    console.log(query);

    let data = [
        {
            id: "PkZNo7MFNFg",
            title: "Learn JavaScript - Full Course for Beginners",
            description:
                "This complete 134-part JavaScript tutorial for beginners will teach you everything you need to know to get started with the JavaScript programming language.",
            channel: "freeCodeCamp.org",
            publishedAt: "2018-12-10T14:13:40Z",
            thumbnail: "https://i.ytimg.com/vi/PkZNo7MFNFg/mqdefault.jpg",
            viewCount: "4821021",
            likeCount: "93390",
            dislikeCount: "1296",
            duration: "PT3H26M43S",
        },
        {
            id: "W6NZfCO5SIk",
            title: "JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour [2020]",
            description:
                "Watch this JavaScript tutorial for beginners to learn JavaScript basics in one hour. Want to master JavaScript? Get my complete JavaScript course: ...",
            channel: "Programming with Mosh",
            publishedAt: "2018-04-24T02:37:33Z",
            thumbnail: "https://i.ytimg.com/vi/W6NZfCO5SIk/mqdefault.jpg",
            viewCount: "3747483",
            likeCount: "63506",
            dislikeCount: "1575",
            duration: "PT48M17S",
        },
        {
            id: "Qqx_wzMmFeA",
            title: "JavaScript Tutorial for Beginners - Full Course in 8 Hours [2020]",
            description:
                "Here is the best free javascript programming course on the planet. Made with lots of ❤️. Take your web development skills to the next level with this Clever ...",
            channel: "Clever Programmer",
            publishedAt: "2019-11-05T16:00:11Z",
            thumbnail: "https://i.ytimg.com/vi/Qqx_wzMmFeA/mqdefault.jpg",
            viewCount: "1341442",
            likeCount: "47944",
            dislikeCount: "983",
            duration: "PT7H57M28S",
        },
        {
            id: "c-I5S_zTwAc",
            title: "Learn JAVASCRIPT in just 5 MINUTES (2020)",
            description:
                "Learn the most important parts of 2020 Javascript in just 5 minutes � NOW OUT: My JavaScript Web Scraping Course! https://JavaScriptWebScraping.com You'll ...",
            channel: "Code Drip by Aaron Jack",
            publishedAt: "2019-12-09T19:15:01Z",
            thumbnail: "https://i.ytimg.com/vi/c-I5S_zTwAc/mqdefault.jpg",
            viewCount: "658770",
            likeCount: "28394",
            dislikeCount: "745",
            duration: "PT5M15S",
        },
        {
            id: "hdI2bqOjy3c",
            title: "JavaScript Crash Course For Beginners",
            description:
                "In this crash course we will go over the fundamentals of JavaScript including more modern syntax like classes, arrow functions, etc. This is the starting point on ...",
            channel: "Traversy Media",
            publishedAt: "2019-03-13T15:46:32Z",
            thumbnail: "https://i.ytimg.com/vi/hdI2bqOjy3c/mqdefault.jpg",
            viewCount: "1359141",
            likeCount: "27749",
            dislikeCount: "278",
            duration: "PT1H40M30S",
        },
        {
            id: "Ukg_U3CnJWI",
            title: "Learn JavaScript in 12 Minutes",
            description:
                "Learn the fundamental features of JavaScript - the language used to add dynamic, interactive content to websites. I teach you how to get started with JavaScript, ...",
            channel: "Jake Wright",
            publishedAt: "2014-08-05T14:30:15Z",
            thumbnail: "https://i.ytimg.com/vi/Ukg_U3CnJWI/mqdefault.jpg",
            viewCount: "2497206",
            likeCount: "52475",
            dislikeCount: "1439",
            duration: "PT12M1S",
        },
        {
            id: "Mus_vwhTCq0",
            title: "JavaScript Pro Tips - Code This, NOT That",
            description:
                "New Series! Code this , not that . Learn how to write solid modern JavaScript and avoid bad code from the olden days. https://angularfirebase.com - Source ...",
            channel: "Fireship",
            publishedAt: "2018-09-27T18:56:49Z",
            thumbnail: "https://i.ytimg.com/vi/Mus_vwhTCq0/mqdefault.jpg",
            viewCount: "1487693",
            likeCount: "69594",
            dislikeCount: "1103",
            duration: "PT12M37S",
        },
        {
            id: "upDLs1sn7g4",
            title: "What is JavaScript?",
            description:
                "What is JavaScript? This short video explains it in 5 minutes. Get the full JavaScript course: http://bit.ly/2M1sp4B Subscribe for more videos: ...",
            channel: "Programming with Mosh",
            publishedAt: "2018-04-24T04:00:17Z",
            thumbnail: "https://i.ytimg.com/vi/upDLs1sn7g4/mqdefault.jpg",
            viewCount: "130950",
            likeCount: "2317",
            dislikeCount: "23",
            duration: "PT5M12S",
        },
        {
            id: "gSnbnYffz7k",
            title: "Modern JavaScript Learning Path in 2020",
            description:
                "Support Patreon - https://www.patreon.com/codevolution Support PayPal - https://www.paypal.me/Codevolution Facebook ...",
            channel: "Codevolution",
            publishedAt: "2020-06-24T12:30:08Z",
            thumbnail: "https://i.ytimg.com/vi/gSnbnYffz7k/mqdefault.jpg",
            viewCount: "132983",
            likeCount: "5742",
            dislikeCount: "80",
            duration: "PT17M19S",
        },
        {
            id: "roumzWd4XJU",
            title: "5 Javascript Projects to Build (For Beginners)",
            description:
                "If you have been learning Javascript from a book or tutorial and haven't built your first project yet then this video is for you. In this video I lay out 5 projects that ...",
            channel: "Andy Sterkowitz",
            publishedAt: "2020-09-07T16:09:37Z",
            thumbnail: "https://i.ytimg.com/vi/roumzWd4XJU/mqdefault.jpg",
            viewCount: "35498",
            likeCount: "2287",
            dislikeCount: "19",
            duration: "PT10M21S",
        },
        {
            id: "bG2BmmYr9NQ",
            title: "The Easiest Javascript Game Ever",
            description:
                "In this video I show you how I created the most basic, simple javascript game that you can make yourself. It's similar to the google dinosaur game that you play ...",
            channel: "KnifeCircus",
            publishedAt: "2020-05-16T17:29:38Z",
            thumbnail: "https://i.ytimg.com/vi/bG2BmmYr9NQ/mqdefault.jpg",
            viewCount: "165034",
            likeCount: "6427",
            dislikeCount: "166",
            duration: "PT8M34S",
        },
        {
            id: "C9Oax_TQaok",
            title: "Javascript Explained! Javascript PRIMER video for beginners.",
            description:
                'So what is Javascript? In this video I take the "10000 foot view" of Javascript and look at the different aspects of Javascript. *** Coaching *** Want to work with me ...',
            channel: "Andy Sterkowitz",
            publishedAt: "2018-07-29T16:00:01Z",
            thumbnail: "https://i.ytimg.com/vi/C9Oax_TQaok/mqdefault.jpg",
            viewCount: "45877",
            likeCount: "1807",
            dislikeCount: "20",
            duration: "PT15M18S",
        },
        {
            id: "Bluxbh9CaQ0",
            title: "JavaScript Основы для Начинающих - Полный Курс за 6 часов [2020]",
            description:
                "Полный практический курс по JavaScript - https://clc.to/senior Таймкоды на все важные разделы JS в описании. Что в курсе: что такое JavaScript, ...",
            channel: "Владилен Минин",
            publishedAt: "2020-05-05T15:00:10Z",
            thumbnail: "https://i.ytimg.com/vi/Bluxbh9CaQ0/mqdefault.jpg",
            viewCount: "714944",
            likeCount: "33608",
            dislikeCount: "322",
            duration: "PT5H47M27S",
        },
        {
            id: "HnXmI2UVZlU",
            title: "This Is the Only Way to Truly Learn JavaScript",
            description:
                "SPONSOR ◅ Linode Cloud Computing ($100.00 CREDIT) http://bit.ly/2HsnivM Check out my latest programming courses! https://www.codehawke.com ...",
            channel: "Chris Hawkes",
            publishedAt: "2019-08-06T22:00:02Z",
            thumbnail: "https://i.ytimg.com/vi/HnXmI2UVZlU/mqdefault.jpg",
            viewCount: "359852",
            likeCount: "10950",
            dislikeCount: "516",
            duration: "PT15M43S",
        },
        {
            id: "uAdpnfe1mGA",
            title: "How to learn JavaScript: 7 tips from my 10 year journey",
            description:
                "Learn Programming https://learnprogramming.online Learn JavaScript https://learnjavascript.online React Tutorial https://react-tutorial.app This video will save ...",
            channel: "Jad Joubran",
            publishedAt: "2020-07-03T09:59:51Z",
            thumbnail: "https://i.ytimg.com/vi/uAdpnfe1mGA/mqdefault.jpg",
            viewCount: "3943",
            likeCount: "190",
            dislikeCount: "3",
            duration: "PT8M31S",
        },
        {
            id: "AB60_uUetJs",
            title: "Will Javascript Take Over the World? | Brian Kernighan and Lex Fridman",
            description:
                "Full episode with Brian Kernighan (Jul 2020): https://www.youtube.com/watch?v=O9upVbGSBFo Clips channel (Lex Clips): https://www.youtube.com/lexclips ...",
            channel: "Lex Fridman",
            publishedAt: "2020-07-20T17:32:20Z",
            thumbnail: "https://i.ytimg.com/vi/AB60_uUetJs/mqdefault.jpg",
            viewCount: "133609",
            likeCount: "5005",
            dislikeCount: "65",
            duration: "PT3M40S",
        },
        {
            id: "6Wzj7kxfRdI",
            title: "5 Must Know Interview Questions for Javascript!",
            description:
                "Land the job! Get help with a resume and cover letter https://gumroad.com/grindreel My Courses: https://grindreel.academy/ Learn Code FREE for 2 months: ...",
            channel: "Joshua Fluke",
            publishedAt: "2018-11-08T07:10:07Z",
            thumbnail: "https://i.ytimg.com/vi/6Wzj7kxfRdI/mqdefault.jpg",
            viewCount: "228210",
            likeCount: "6890",
            dislikeCount: "474",
            duration: "PT11M40S",
        },
        {
            id: "ylakWC0VcEM",
            title: "Как выучить JavaScript? Самый аху#### способ!",
            description:
                "Хочешь выучить JavaScript, но понятия не имеешь как?! Изи, лови методичку ;) Крутой видеокурс по JavaScript: ...",
            channel: "Хауди Хо™ - Просто о мире IT!",
            publishedAt: "2019-04-04T17:34:52Z",
            thumbnail: "https://i.ytimg.com/vi/ylakWC0VcEM/mqdefault.jpg",
            viewCount: "497446",
            likeCount: "32518",
            dislikeCount: "1021",
            duration: "PT10M15S",
        },
        {
            id: "Bv_5Zv5c-Ts",
            title: "JavaScript: Understanding the Weird Parts - The First 3.5 Hours",
            description:
                "Full 12 hour course on sale for $15.99! https://www.udemy.com/course/understand-javascript/?couponCode=CB2557F420F5A14CBB49 (normal price $149) ...",
            channel: "Tony Alicea",
            publishedAt: "2015-04-03T01:14:59Z",
            thumbnail: "https://i.ytimg.com/vi/Bv_5Zv5c-Ts/mqdefault.jpg",
            viewCount: "3729178",
            likeCount: "31148",
            dislikeCount: "1537",
            duration: "PT3H32M50S",
        },
        {
            id: "aIpjE4Q3w-Y",
            title: "Javascript vs Python THROWDOWN - Which should YOU use? (2020)",
            description:
                "There are so many programming languages out there that it can be overwhelming to know which is right for your project. Picking the right language is crucial for ...",
            channel: "Kite",
            publishedAt: "2020-03-13T17:45:00Z",
            thumbnail: "https://i.ytimg.com/vi/aIpjE4Q3w-Y/mqdefault.jpg",
            viewCount: "63083",
            likeCount: "1385",
            dislikeCount: "179",
            duration: "PT6M54S",
        },
    ];

    setTimeout(() => {
        cb(data);
    }, 500);
};
